INITIAL_PROJECT_REPO = "git@gitlab.com:getindata/streaming-labs/flink-sandbox-python.git"
PROJECT_LOCAL_CONFIG_FILE_NAME = ".streaming_config.yml"
PROJECT_K8S_CONFIGMAP_KEY = "project_configmap.json"
PLATFORM_K8S_CONFIGMAP_NAME = "streaming-platform-config"
PLATFORM_K8S_CONFIGMAP_KEY = "platform_config.json"
PLATFORM_K8S_SECRET_NAME = "streaming-platform-secret"
