repos:

- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
    - id: isort

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
    - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
    - id: check-merge-conflict
    - id: debug-statements
    - id: name-tests-test
      args: ['--django']  # PyCharm requires tests to have 'test' as prefix, not a suffix
    - id: check-json

- repo: https://github.com/pycqa/flake8
  rev: 5.0.4
  hooks:
    - id: flake8
      args: [--max-line-length=120, --exclude *.yml]
      additional_dependencies: [
        'flake8-blind-except',
        'flake8-comprehensions',
        'flake8-pep3101',
      ]

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.971
  hooks:
    - id: mypy
      additional_dependencies:
        - 'types-requests'