name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2.2.1
      with:
        python-version: 3.8

    - name: Setup virtualenv
      run: |
        python -V
        python -m pip install virtualenv
        virtualenv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv lock -r > requirements.txt
        pip install -r requirements.txt

    - name: Build
      run: |
        python setup.py sdist bdist_wheel

    - name: Test with pytest
      run: |
        pip install pytest
        pytest