name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8

      - name: Setup virtualenv
        run: |
          python -V
          python -m pip install pipenv
          pipenv requirements > requirements.txt

      - name: Check pre-commit status
        run: |
          pip install pre-commit==2.15.0
          pre-commit run --all-files

      - name: Test
        run: |
          pip install pipenv
          pipenv install --dev
          pipenv run pytest

      - name: Wheel
        run: |
          python setup.py sdist

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.PUBLIC_GCR_DEPLOY_SA_KEY }}

      - name: Build docker image using public pypi package
        uses: docker/build-push-action@v4
        with:
          context: release
          build-args: |
            PYTHON_VERSION=3.8
            STREAMING_CLI_VERSION=1.9.0
          build-contexts: |
            context=docker-image://docker:stable-git
          push: true
          tags: gcr.io/getindata-images-public/streaming-cli:1.9.0